# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alert_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
