# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_task_alert_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alert_time',
        ),
        migrations.AddField(
            model_name='task',
            name='alert_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
