# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20180811_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alert_hour',
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
    ]
